#!/usr/bin/env python3
"""Build the same navigation/search for pages that do not use the full main script."""
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
main = (ROOT / 'main.js').read_text()
nav = main[main.index('  // ─── Nav: scroll shadow'):main.index('  // ─── Scroll animations')]
search = main[main.index('/* ═══════════════════════════════════════════════════\n   QUICK FIND'):]
(ROOT / 'assets/site-navigation.js').write_text('// Generated by scripts/build-shared-navigation.py; edit main.js.\n(function () {\n' + nav + '\n})();\n\n' + search)
css = (ROOT / 'style.css').read_text()
start = css.index('.qf-overlay {')
end = css.index('/* ─── SERVICES GRID DIAGNOSTIC TICKET CARDS', start)
(ROOT / 'assets/css/quick-find.css').write_text('/* Generated from style.css by scripts/build-shared-navigation.py. */\n' + css[start:end])
print('Shared navigation and Quick Find assets built.')
